// Auto-generated test entry point
export { runAllTests, formatSuiteResultsText, clearTests } from './src/tests/testHarness.js';
import './src/tests/unit/anthropic-conversion.test.ts';
import './src/tests/unit/anthropic-service-mock.test.ts';
import './src/tests/unit/claude-integration.test.ts';
import './src/tests/unit/codeRendererStreaming.unit.test.ts';
import './src/tests/unit/complete-model-flow-simulation.test.ts';
import './src/tests/unit/conversation-switching-race.test.ts';
import './src/tests/unit/ctrlEnterSend.test.ts';
import './src/tests/unit/debug-store-state.test.ts';
import './src/tests/unit/debugLayerLogger.unit.test.ts';
import './src/tests/unit/dom-dropdown-state-analysis.test.ts';
import './src/tests/unit/draft-isolation.test.ts';
import './src/tests/unit/e2e-helper-validation.test.ts';
import './src/tests/unit/keyboardSettings.test.ts';
import './src/tests/unit/messageModelLabeling.unit.test.ts';
import './src/tests/unit/provider-model-filtering.test.ts';
import './src/tests/unit/reasoning-window-conversation-id.test.ts';
import './src/tests/unit/reasoningPayload.test.ts';
import './src/tests/unit/responsesConversionAndPayload.test.ts';
import './src/tests/unit/settings-provider-filtering-tdd.test.ts';
import './src/tests/unit/sseParserDebugLogging.unit.test.ts';
import './src/tests/unit/streaming-error-recovery.test.ts';