// Auto-generated test entry point
export { runAllTests, formatSuiteResultsText, clearTests } from './src/tests/testHarness.js';
import './src/tests/unit/anthropic-conversion.test.ts';
import './src/tests/unit/anthropic-service-mock.test.ts';
import './src/tests/unit/claude-integration.test.ts';
import './src/tests/unit/codeRendererStreaming.unit.test.ts';
import './src/tests/unit/complete-model-flow-simulation.test.ts';
import './src/tests/unit/ctrlEnterSend.test.ts';
import './src/tests/unit/debug-store-state.test.ts';
import './src/tests/unit/dom-dropdown-state-analysis.test.ts';
import './src/tests/unit/draft-isolation.test.ts';
import './src/tests/unit/e2e-helper-validation.test.ts';
import './src/tests/unit/keyboardSettings.test.ts';
import './src/tests/unit/messageModelLabeling.unit.test.ts';
import './src/tests/unit/provider-model-filtering.test.ts';
import './src/tests/unit/reasoningPayload.test.ts';
import './src/tests/unit/responsesConversionAndPayload.test.ts';
import './src/tests/unit/settings-provider-filtering-tdd.test.ts';
import './src/tests/unit/streaming-error-recovery.test.ts';
import './src/tests/live/01-api-key-smoke-test.test.ts';
import './src/tests/live/02-anthropic-service-test.test.ts';
import './src/tests/live/03-settings-integration-test.test.ts';
import './src/tests/live/04-anthropic-messaging-test.test.ts';
import './src/tests/live/05-anthropic-error-handling-live.test.ts';
import './src/tests/live/06-openai-error-handling-live.test.ts';
import './src/tests/live/07-openai-raw-api-test.test.ts';